version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend/Web/subi-web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend/API/SubiAPI
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
